<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="22918" started-at="2020-03-19T05:17:47Z" finished-at="2020-03-19T05:18:10Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="22918" started-at="2020-03-19T05:17:47Z" finished-at="2020-03-19T05:18:10Z">
      <class name="TestIng.Tests">
        <test-method status="PASS" signature="Prerequiste()[pri:0, instance:TestIng.Tests@9353778]" name="Prerequiste" is-config="true" duration-ms="177" started-at="2020-03-19T10:47:47Z" finished-at="2020-03-19T10:47:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Prerequiste -->
        <test-method status="PASS" signature="setup()[pri:0, instance:TestIng.Tests@9353778]" name="setup" is-config="true" duration-ms="16782" started-at="2020-03-19T10:47:47Z" finished-at="2020-03-19T10:48:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="first()[pri:1, instance:TestIng.Tests@9353778]" name="first" duration-ms="139" started-at="2020-03-19T10:48:03Z" finished-at="2020-03-19T10:48:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- first -->
        <test-method status="FAIL" signature="second()[pri:2, instance:TestIng.Tests@9353778]" name="second" duration-ms="5009" started-at="2020-03-19T10:48:04Z" finished-at="2020-03-19T10:48:09Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [nopCommerce demo store.j Login] but found [nopCommerce demo store]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [nopCommerce demo store.j Login] but found [nopCommerce demo store]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at TestIng.Tests.second(Tests.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- second -->
        <test-method status="SKIP" signature="third()[pri:3, instance:TestIng.Tests@9353778]" name="third" duration-ms="8" started-at="2020-03-19T10:48:09Z" finished-at="2020-03-19T10:48:09Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[skipping this test]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: skipping this test
	at TestIng.Tests.third(Tests.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- third -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:TestIng.Tests@9353778]" name="teardown" is-config="true" duration-ms="733" started-at="2020-03-19T10:48:09Z" finished-at="2020-03-19T10:48:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="PASS" signature="flush()[pri:0, instance:TestIng.Tests@9353778]" name="flush" is-config="true" duration-ms="579" started-at="2020-03-19T10:48:10Z" finished-at="2020-03-19T10:48:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flush -->
      </class> <!-- TestIng.Tests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
